name: Build Operator and CA generator

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  id-token: write
  contents: read
  packages: writen writen writen

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main

  package-ca-gen:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      docker-context: "./chiaca-generator"
      dockerfile: "./chiaca-generator/Dockerfile"
      image_subpath: "ca-gen"
